### ISSUE TITLE
GitHub dependency doesn't get generated if subdir is not set

### ISSUE THREAD

**Issue by poscat0x04** [input-output-hk/nix-tools#82]
for example this will generate cabal-helper.nix
```
- github: jneira/cabal-helper
   commit: ffb1f57a5ffc6b7ac3c46a9974c4420a6d2bb9b2
   subdirs:
     - .
```
where as this wont
```
- github: jneira/cabal-helper
   commit: ffb1f57a5ffc6b7ac3c46a9974c4420a6d2bb9b2
```
